language: python
dist: trusty

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

before_install:

  # Add needed repositories
  - sudo add-apt-repository ppa:gambas-team/gambas3 -y
  # - sudo add-apt-repository ppa:webupd8team/java -y
  - sudo add-apt-repository ppa:linuxuprising/java -y
  - sudo add-apt-repository ppa:mc3man/gstffmpeg-keep -y
  - sudo apt-get update -qq

  # Install and upgrade java to v11 (for Filebot)
  - sudo apt-get install -y oracle-java11-installer oracle-java11-set-default -qq
  - echo oracle-java11-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  - sudo update-java-alternatives -s java-11-oracle

  # DBUS fixes for ABC
  - sudo apt-get install -y dbus -qq
  - export DISPLAY=:0
  - eval $(dbus-launch --sh-syntax)
  - export DBUS_SESSION_BUS_ADDRESS
  - export DBUS_SESSION_BUS_PID

install:

  # ABC dependencies
  - sudo apt-get install -y ia32* gstreamer0.10* build-essential -qq
  - sudo apt-get install -y gambas3 cdrdao flac mkcue cuetools shntool php5-cli vlc gstreamer-tools gstreamer0.10-fluendo-mp3 gpac -qq

  # Deluge dependencies
  - pip install twisted pyOpenSSL chardet pyxdg

  # Music handler dependencies
  - pip install requests mutagen beets
  - pip install pylast==2.3.0

  # Book handler dependencies
  - pip install google-api-python-client

  # Testing dependencies
  - pip install unittest2 responses mock coveralls

before_script:

  # Deluge
  - git clone git://deluge-torrent.org/deluge.git; cd deluge;
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then git checkout -b 1.3-stable origin/1.3-stable; else git checkout develop; fi
  - python setup.py clean -a; python setup.py build; python setup.py install; cd

  # Filebot
  - wget https://emorel.li/dl/FileBot_4.8.2_amd64.deb
  - sudo dpkg -i FileBot_4.8.2_amd64.deb;

  # NeroACC - ABC dependency
  - mkdir aac; cd aac; wget https://emorel.li/dl/NeroAACCodec-1.5.1.zip
  - unzip -j NeroAACCodec-1.5.1.zip; cd linux; sudo install -D -m755 neroAacEnc /usr/bin/; cd

  # mp4v2 - ABC dependency
  - mkdir mp4v2; cd mp4v2/; wget https://emorel.li/dl/mp4v2-1.9.1.tar.bz2
  - tar -xf ./mp4v2-1.9.1.tar.bz2; cd mp4v2-1.9.1
  - ./configure; make; sudo make install
  - sudo ln -s /usr/local/lib/libmp4v2.so.1.9.1 /usr/lib/libmp4v2.so.1; cd

  # ABC
  - wget https://emorel.li/dl/abc_0.0.4-0ubuntu1_all.deb -O abc_0.0.4-0ubuntu1_all.deb
  - sudo dpkg -i abc_0.0.4-0ubuntu1_all.deb

  # Clean Up
  - sudo apt-get -f install
  - cd ~/build/ErinMorelli/em-media-handler

script:

  # Install mediahandler
  - python ./setup.py install

  # Run test suite
  - coverage run --source=mediahandler setup.py test

after_success:

  # Send coverage results to coveralls
  coveralls
