General:
    keep_files: no
    keep_if_skips: yes

Deluge:
    enabled: no
    ssl: no
    host: localhost
    endpoint: /json

Logging:
    enabled: yes
    level: 30
    log_file:

Notifications:
    enabled: no
    notify_name:
    pushover:
        api_key:
        user_key:
    pushbullet:
        token:

TV:
    enabled: yes
    folder:
    ignore_subs: yes
    format: '{n}/Season {s}/{n.space(".")}.{"S"+s.pad(2)}E{e.pad(2)}'
    log_file:

Movies:
    enabled: yes
    folder:
    ignore_subs: yes
    format: '{n} ({y})'
    log_file:

Music:
    enabled: no
    log_file:

Audiobooks:
    enabled: no
    folder:
    api_key:
    make_chapters: off
    chapter_length: 8
